export const EXPO_PUBLIC_APPWRITE_PROJECT_ID =
	process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID;
export const EXPO_PUBLIC_APPWRITE_PROJECT_NAME =
	process.env.EXPO_PUBLIC_APPWRITE_PROJECT_NAME;
export const EXPO_PUBLIC_APPWRITE_ENDPOINT =
	process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT;
export const EXPO_PUBLIC_BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL;
export const EXPO_PUBLIC_APPWRITE_BUCKET_ID =
	process.env.EXPO_PUBLIC_APPWRITE_BUCKET_ID;

export const EXPO_PUBLIC_REVENUECAT_IOS_API_KEY =
	process.env.EXPO_PUBLIC_REVENUECAT_IOS_API_KEY;
export const EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY =
	process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY;
export const EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID =
	process.env.EXPO_PUBLIC_REVENUECAT_ENTITLEMENT_ID;
