export const status = {
  streaks: 5,
  gems: 450,
  vipStatus: false,
};

export const cards = [
  {
    title: "Senior UX Designer",
    industry: "Design",
    difficulty: "Hard",
    questions: 6,
    review: 4.8,
    reviewCount: 120,
    focusArea: "User Research & Interaction Design",
    isFavourite: true,
  },
  {
    title: "Entry-Level Product Manager",
    industry: "Manager",
    difficulty: "Easy",
    questions: 5,
    review: 4.5,
    reviewCount: 89,
    focusArea: "Product Strategy & Roadmapping",
    isFavourite: false,
  },
  {
    title: "Intermediate Software Engineer",
    industry: "IT",
    difficulty: "Medium",
    questions: 7,
    review: 4.7,
    reviewCount: 156,
    focusArea: "Software Development & Architecture",
    isFavourite: false,
  },
  {
    title: "Junior Data Analyst",
    industry: "Data",
    difficulty: "Easy",
    questions: 8,
    review: 4.6,
    reviewCount: 95,
    focusArea: "Data Visualization & SQL",
    isFavourite: false,
  },
  {
    title: "Senior DevOps Engineer",
    industry: "IT",
    difficulty: "Hard",
    questions: 10,
    review: 4.9,
    reviewCount: 210,
    focusArea: "CI/CD & Cloud Infrastructure",
    isFavourite: false,
  },
  {
    title: "Mid-Level Marketing Specialist",
    industry: "Marketing",
    difficulty: "Medium",
    questions: 3,
    review: 4.4,
    reviewCount: 78,
    focusArea: "Digital Marketing & Analytics",
    isFavourite: false,
  },
  {
    title: "Entry-Level Graphic Designer",
    industry: "Design",
    difficulty: "Easy",
    questions: 4,
    review: 4.3,
    reviewCount: 67,
    focusArea: "Branding & Visual Design",
    isFavourite: false,
  },
  {
    title: "Senior Product Owner",
    industry: "Manager",
    difficulty: "Hard",
    questions: 5,
    review: 4.7,
    reviewCount: 134,
    focusArea: "Agile Practices & Stakeholder Management",
    isFavourite: false,
  },
];

export const FeaturedCards = [
  {
    title: "Senior UX Designer",
    industry: "Design",
    difficulty: "Hard",
    questions: 6,
    review: 4.7,
    reviewCount: 120,
    focusArea: "User Research & Interaction Design",
  },
  {
    title: "Entry-Level Product Manager",
    industry: "Manager",
    difficulty: "Easy",
    questions: 5,
    review: 4.5,
    reviewCount: 89,
    focusArea: "Product Strategy & Roadmapping",
  },
  {
    title: "Intermediate Software Engineer",
    industry: "IT",
    difficulty: "Medium",
    questions: 7,
    review: 4.9,
    reviewCount: 156,
    focusArea: "Software Development & Architecture",
  },
];

export const industries = [
  "IT",
  "Data",
  "Sales",
  "Finance",
  "Design",
  "Manager",
  "Marketing",
];
